<?php
require_once __DIR__ . '/../config/functions.php'; exigirLogin();
$id=(int)($_GET['id']??0); $erro='';
$categorias=$pdo->query('SELECT id,nome FROM categorias ORDER BY nome')->fetchAll();
$item=['categoria_id'=>'','titulo'=>'','resposta'=>'','palavras_chave'=>'','ativo'=>1];
if($id){$st=$pdo->prepare('SELECT * FROM conteudos WHERE id=?');$st->execute([$id]);$item=$st->fetch() ?: $item;}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $categoria=(int)($_POST['categoria_id']??0); $titulo=trim($_POST['titulo']??''); $resposta=trim($_POST['resposta']??''); $palavras=trim($_POST['palavras_chave']??''); $ativo=isset($_POST['ativo'])?1:0;
  if(!$categoria||$titulo===''||$resposta==='') $erro='Preencha categoria, título/pergunta e resposta.';
  else { if($id){$st=$pdo->prepare('UPDATE conteudos SET categoria_id=?,titulo=?,resposta=?,palavras_chave=?,ativo=? WHERE id=?');$st->execute([$categoria,$titulo,$resposta,$palavras,$ativo,$id]);}else{$st=$pdo->prepare('INSERT INTO conteudos(categoria_id,titulo,resposta,palavras_chave,ativo) VALUES(?,?,?,?,?)');$st->execute([$categoria,$titulo,$resposta,$palavras,$ativo]);} header('Location: index.php?ok=1');exit; }
  $item=array_merge($item,['categoria_id'=>$categoria,'titulo'=>$titulo,'resposta'=>$resposta,'palavras_chave'=>$palavras,'ativo'=>$ativo]);
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $id?'Editar':'Novo' ?> conteúdo - IFC Assist</title><link rel="stylesheet" href="../assets/style.css"></head><body><header class="topo"><div class="marca"><div class="logo">IFC</div><div><strong>IFC Assist</strong><span>Administração</span></div></div><a class="admin-link" href="index.php">← Painel</a></header><main class="container"><section class="form-card"><p class="eyebrow">Base de conhecimento</p><h1><?= $id?'Editar conteúdo':'Novo conteúdo' ?></h1><?php if($erro): ?><div class="erro"><?=e($erro)?></div><?php endif; ?><form method="post"><label>Categoria<select name="categoria_id" required><option value="">Selecione</option><?php foreach($categorias as $cat): ?><option value="<?=$cat['id']?>" <?=$item['categoria_id']==$cat['id']?'selected':''?>><?=e($cat['nome'])?></option><?php endforeach; ?></select></label><label>Pergunta ou título<input name="titulo" value="<?=e($item['titulo'])?>" required maxlength="180"></label><label>Resposta<textarea name="resposta" rows="7" required><?=e($item['resposta'])?></textarea></label><label>Palavras-chave<input name="palavras_chave" value="<?=e($item['palavras_chave'])?>" maxlength="255" placeholder="sala, localização, onde fica"></label><label class="check"><input type="checkbox" name="ativo" <?=$item['ativo']?'checked':''?>> Conteúdo ativo</label><button class="botao full" type="submit">Salvar</button></form></section></main></body></html>
